debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: kjs
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      jdbc-url:
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate.default_batch_fetch_size: 100
  h2.console.enabled: false
  sql.init.mode: always

data.rest:
  base-path: /api
  detection-strategy: annotated

  spring:
    config.activate.on-profile: testdb
    datasource:
      url: jdbc:h2:mem:board;mode=mysql
      driverClassName: org.h2.Driver
    sql.init.mode: always
    test.database.replace: nones
